version: '3'
services:
  phoenix:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db

  svelte:
    build: ./frontend
    ports:
      - "5000:5000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: